export default {
  PRIMARY_COLOR: '#0090DF',
  PRIMARY_COLOR_DARK: '#005FAB',
  GREEN_COLOR: '#52E0A0',
  LIGTH_BLUE_COLOR: '#52C0F2',
  MUSTARD_COLOR: '#FCD581',
  RED_COLOR: '#D52941',
  WHITE_COLOR: '#F5F5F5',
  BACKGROUND_BOTOM: '#0071bf',
  GRAY_COLOR: '#edf6fb',
  GRAY_TEXT_COLOR: '#464545',
  STATUS_BAR_COLOR: '#0070bd',
  LIST_COLORS: ['MUSTARD_COLOR', 'RED_COLOR', 'GREEN_COLOR'],
  BACKGROUNDIMAGE: {
    flex: 1,
    resizeMode: 'cover',
    width: '100%',
    alignItems: 'center',
  },
};
